### ISSUE TITLE
shawlaf ban manager will not load, Here is the error

### ISSUE THREAD

**Issue by Riyrus1** [shawlaf/Banmanager#3]
The plugin will not load, I have BungeeUtil and I am loading this onto a bungee cord proxy.

12:02:21 [WARNING] Error enabling plugin ShawlafsBanmanager
java.lang.UnsupportedClassVersionError: me/shawlaf/banmanager/Banmanager has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:34)
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:304)
at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:212)
at net.md_5.bungee.BungeeCord.start(BungeeCord.java:264)
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by inventor02** [comment]
Java version 53.0 is Java 9 - it seems like you have Java 8 (52.0). You’ll need to upgrade.

**Comment by shawlaf** [comment]
didn't notice I compiled with Java 9, I'll compile with Java 8 and update later

**Comment by shawlaf** [comment]
This was fixed here: https://github.com/shawlaf/Banmanager/releases/tag/1.0.1-RELEASE
