### ISSUE TITLE
Banmanager failed to load.

### ISSUE THREAD

**Issue by Firav** [shawlaf/Banmanager#5]
Plugin fails to load with fresh install. Dependencies are included and loaded successfully.

Stacktrace:
```
11:11:05 [WARNING] Error enabling plugin ShawlafsBanmanager
java.lang.NoClassDefFoundError: me/shawlaf/banmanager/managers/database/sql/SqlConnectionManager
	at me.shawlaf.banmanager.managers.database.DatabaseManager.<init>(DatabaseManager.java:37)
	at me.shawlaf.banmanager.Banmanager.onLoad(Banmanager.java:70)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:309)
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:212)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:257)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: me.shawlaf.banmanager.managers.database.sql.SqlConnectionManager
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 7 more
```

**Comment by Firav** [comment]
Also attempted to start plugin with just the plugin itself and the dependency.

**Comment by Firav** [comment]
Version: 1.0.1-RELEASE

**Comment by shawlaf** [comment]
The class was not included in the compiled jar for some reason, fixed here:https://github.com/shawlaf/Banmanager/releases/tag/1.0.1.1-RELEASE
