### ISSUE TITLE
Permissions not functional

### ISSUE THREAD

**Issue by Firav** [shawlaf/Banmanager#6]
Hello again. 
I have set up the permissions as so within Bungee.
The default Bungee commands work fine. Anything to do with BanManager returns a "cannot access command" error.

```
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - banmanager.punish.info.viewbasic
  - banmanager.punish.info.view_ip
  - banmanager.command.punish
  - banmanager.punish.ban
  - banmanager.punish.mute
  - banmanager.punish.kick
  - banmanager.punish.warn
  - banmanager.punish.permanent
  - banmanager.punish.remove.own
  - banmanager.punish.remove.other
  - banmanager.punish.remove.purge
  - banmanager.database.fetchmojang
  - banmanager.punish.admintoggle
  - banmanager.punish.edit.length
  - banmanager.punish.edit.reason
  - banmanager.punish.edit.reactivate
```

**Comment by shawlaf** [comment]
Install the newest version and reply if the problem still occurs: https://github.com/shawlaf/Banmanager/releases/tag/1.1.0

**Comment by Firav** [comment]
The commands now partially work.
I tested the commands /punish and /warn and both thew exceptional errors.
Stacktrace:

```
12:09:09 [INFO] Firav executed command: /p
12:09:13 [INFO] Firav executed command: /punish Firav
12:09:16 [INFO] Firav executed command: /punish Firav test
12:09:16 [INFO] com.mysql.jdbc.JDBC42PreparedStatement@6e35598c: SELECT uuid FRO
M ips WHERE ip = '150.156.212.162';
12:09:16 [INFO] com.mysql.jdbc.JDBC42PreparedStatement@5ec2e82: SELECT uuid FROM
 ips WHERE ip = '150.156.210.170';
12:09:16 [WARNING] Error in dispatching command
java.lang.RuntimeException: java.lang.ClassCastException: net.md_5.bungee.UserCo
nnection cannot be cast to dev.wolveringer.bungeeutil.player.Player
12:09:38 [INFO] Firav executed comma##### Heap utilization statistics [MB] #####
12:09:38 [WARNING] Error in dispatch#     Reserved Used Memory:      59   M    #
java.lang.RuntimeException: java.lan#     Reserved Free Memory:      172  M    #
    at me.shawlaf.cmdlibbungee.Abstr#     Reserved Memory:           231  M    #
    at me.shawlaf.cmdlibbungee.Abstr#     ----------------------------------   #
)                                   #     Allowed Reservable Memory: 3620 M    #
    at net.md_5.bungee.api.plugin.Pl############################################
va:169)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.ja
va:116)
    at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:140)

    at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:50)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abstract
ChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abstract
ChannelHandlerContext.java:348)
 andlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractCh
annelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultCh
annelPipeline.java:1359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abstract
ChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abstract
ChannelHandlerContext.java:348)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPip
eline.java:935)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNi
oByteChannel.java:138)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:64
5)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLo
op.java:580)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:4
97)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEven
tExecutor.java:858)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
    at me.shawlaf.banmanager.core.database.util.DatabaseQuery.generateSql(Databa
seQuery.java:52)
    at me.shawlaf.banmanager.core.database.util.DatabaseQuery.execute(DatabaseQu
ery.java:74)
    at me.shawlaf.banmanager.core.database.util.DatabaseQuery.execute(DatabaseQu
ery.java:70)
    at me.shawlaf.banmanager.core.managers.database.punish.MysqlPunishmentDataba
se.doesPunishmentExist(MysqlPunishmentDatabase.java:152)
    at me.shawlaf.banmanager.core.managers.database.punish.MysqlPunishmentDataba
se.putPunishment(MysqlPunishmentDatabase.java:135)
    at me.shawlaf.banmanager.core.managers.database.PunishmentDatabase.putPunish
ment(PunishmentDatabase.java:27)
    at me.shawlaf.banmanager.proxy.implementation.punish.CraftPunishment.save(Cr
aftPunishment.java:396)
    at me.shawlaf.banmanager.proxy.implementation.punish.CraftPunishment.<init>(
CraftPunishment.java:161)
    at me.shawlaf.banmanager.proxy.implementation.punish.CraftPunishment.createN
ew(CraftPunishment.java:47)
    at me.shawlaf.banmanager.proxy.command.CommandWarn.execute(CommandWarn.java:
38)
    at me.shawlaf.cmdlibbungee.AbstractCommand.lambda$handle$0(AbstractCommand.j
ava:134)
    at me.shawlaf.cmdlibbungee.AbstractCommand.handle(AbstractCommand.java:137)
    ... 45 more
>
```

**Comment by Firav** [comment]
Also, version that is displayed in console is still 1.0.1-RELEASE.

**Comment by shawlaf** [comment]
Version is still displayed as 1.0.1-RELEASe, because I forgot to update it in bungee.yml

Can you send me the stacktrace from the proxy.log.0 file directly? BungeeUtils Memory stats are covering up the line where the error happened.

**Comment by shawlaf** [comment]
this might be an issue with mysql, which I haven't tested in a while, I'll investigate
