### ISSUE TITLE
Punishment command not functioning

### ISSUE THREAD

**Issue by Firav** [shawlaf/Banmanager#9]
Upon performing the command, the following stacktrace is thrown.

```
20:00:11 [INFO] Firav executed command: /p Firav General Hacking
20:00:11 [WARNING] Error in dispatching command
java.lang.RuntimeException: java.lang.ClassCastException: net.md_5.bungee.UserConnection cannot be cast to dev.wolveringer.bungeeutil.player.Player
	at me.shawlaf.cmdlibbungee.AbstractCommand.handle(AbstractCommand.java:142)
	at me.shawlaf.cmdlibbungee.AbstractCommand$1.execute(AbstractCommand.java:74)
	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:169)
	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:116)
	at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:140)
	at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:50)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: net.md_5.bungee.UserConnection cannot be cast to dev.wolveringer.bungeeutil.player.Player
	at me.shawlaf.banmanager.proxy.gui.UserInterface.open(UserInterface.java:121)
	at me.shawlaf.banmanager.proxy.command.CommandPunish.execute(CommandPunish.java:33)
	at me.shawlaf.cmdlibbungee.AbstractCommand.lambda$handle$0(AbstractCommand.java:134)
	at me.shawlaf.cmdlibbungee.AbstractCommand.handle(AbstractCommand.java:137)
	... 45 more
```

**Comment by shawlaf** [comment]
the error is caused by me casting a proxiedplayer to a player (class within bungeeutil), something that the bungeeutil wiki says is safe to do: https://github.com/WolverinDEV/BungeeUtil/wiki/General-extra-functions

restart the server and see if the problem persists, if yes: reinstall bungeeutil, if that still does not fix the issue, contact me again

**Comment by shawlaf** [comment]
could it be that another plugin you installed is creating instances of proxiedplayer which cannot be cast to bungeeutils player?

**Comment by Firav** [comment]
Confirmed conflict with plugin "BungeeAdvancedMotd-Beta_1.2"

**Comment by Firav** [comment]
Any way that this conflict could be fixed? Or should I just find an alternative.

**Comment by shawlaf** [comment]
i will look for a way to get a bungeeutil player object if casting is not an option i.e. when `proxiedPlayer instanceof Player` is false

**Comment by shawlaf** [comment]
Try to recreate the error with [This jar](https://gist.github.com/shawlaf/2ccd52c4f0e516c959fb19b7578520c0/raw/54e7a47d098fc50b0d5cbf504c0355b5d3a5aa16/Banmanager-1.1.2-INDEV.jar)

**Comment by Firav** [comment]
Stack:

```
11:41:14 [INFO] Firav executed command: /p Firav test
11:41:14 [WARNING] Error in dispatching command
java.lang.RuntimeException: java.lang.ClassCastException: net.md_5.bungee.UserConnection cannot be cast to dev.wolveringer.bungeeutil.player.Player
	at me.shawlaf.cmdlibbungee.AbstractCommand.handle(AbstractCommand.java:149)
	at me.shawlaf.cmdlibbungee.AbstractCommand$1.execute(AbstractCommand.java:81)
	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:169)
	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:116)
	at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:140)
	at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:50)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: net.md_5.bungee.UserConnection cannot be cast to dev.wolveringer.bungeeutil.player.Player
	at me.shawlaf.banmanager.proxy.Banmanager.getBungeeUtilPlayer(Banmanager.java:202)
	at me.shawlaf.banmanager.proxy.gui.UserInterface.open(UserInterface.java:121)
	at me.shawlaf.banmanager.proxy.command.CommandPunish.execute(CommandPunish.java:34)
	at me.shawlaf.cmdlibbungee.AbstractCommand.lambda$handle$0(AbstractCommand.java:141)
	at me.shawlaf.cmdlibbungee.AbstractCommand.handle(AbstractCommand.java:144)
	... 45 more
```

**Comment by shawlaf** [comment]
any other stack traces before you run the command i.e. on startup?

**Comment by shawlaf** [comment]
BungeeUtil itself seems to be incompatible with BungeeAdvancedMotd.

**Comment by Firav** [comment]
Alright. I'll find an alternative. You must be sick of me by now.

**Comment by shawlaf** [comment]
no, it's fine. I'd rather have people report issues rather than staying quiet about them.

**Comment by Firav** [comment]
Issue resolved.
BungeeUtil incompatibility with BungeeAdvancedMOTD.
No fault in BanManager.
